@baseUrl = http://localhost:3000
@authToken = {{login.response.body.data.token}}
@id = "6118c7ec-58bf-41f0-a0e4-4857b43321f6"
@userId = {{login.response.body.data.user.id}}

### Auth - Login
# @name login
POST {{baseUrl}}/api/v1/auth/login
Content-Type: application/json

{
  "email": "superadmin@example.com",
  "password": "change-me-strongly"
}

### Audit - Get All
GET {{baseUrl}}/api/v1/audit
Authorization: Bearer {{authToken}}

### Audit - Get By ID
GET {{baseUrl}}/api/v1/audit/{{id}}
Authorization: Bearer {{authToken}}

### Audit - Get By User
GET {{baseUrl}}/api/v1/audit/user/{{userId}}
Authorization: Bearer {{authToken}}

### Audit - Get By Entity
GET {{baseUrl}}/api/v1/audit/entity/User/{{userId}}
Authorization: Bearer {{authToken}}
